export const ActionTypes={
 GET_ALL_DATA:"GET_ALL_DATA",
 REMOVE_SELECTED_DATA:"REMOVE_SELECTED_DATA",
 LOADING_DATA:"LOADING_DATA",
 NO_DATA:"NO_DATA",
 FILTER_DATA_BY_ALPHABET:"FILTER_DATA_BY_ALPHABET",
 INSERT_DATA:"INSERT_DATA"
};